CREATE DATABASE UserDB;
GO

USE UserDB;
GO

CREATE TABLE dbo.Users
(
    UserId   INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(64) NOT NULL,
    Email    NVARCHAR(100) NULL,
    FullName NVARCHAR(100) NULL,
    Birthday DATE NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO
